### ISSUE TITLE
Prototype TODO List

### ISSUE THREAD

**Issue by RuyerZ** [RujiaZhang/TurretAgent#2]
# Hero - Ian WIP
- [x] Assets
- [x] Use mouse to control gun direction and shooting
- [x] WASD movement
- [x] Deploy and undeploy turret

# Turret - ZRJ
- [x] Assets
- [x] Gun rotate
- [x] Auto shooting

# Enemy
- [x] Assets
- [x] Move in a fixed route - SY
- [x] Shoot
