### ISSUE TITLE
Beta TODO List

### ISSUE THREAD

**Issue by RuyerZ** [RujiaZhang/TurretAgent#61]
- [x] 游戏Pause/Resume 
- [x] Fix带枪的敌人的动画
- [x] 击杀敌人能得到一定数目的金钱（剧情和Image上不一定是金币，可以是电力之类的）
  - 结算统一放在HPBehavior里
- [x] 一次性RPG、地雷道具
- [x] TurretUpgrade接口
  - ```List<[string,float]> UpgradeOptions()```: 返回一个(升级名称，升级cost)的list
  - ```bool Upgrade(int index)```: 升级第i个选项，返回值为升级成功
- [x] 实现基本Turret的TurretUpgradeBehavior
- [x] FriendManager，管理当前所有Turret和友军单位（暂未实现）
  - GetClosestTurret: 返回最近的Turret
- [x] ~~角色持有扳手按右键打开升级UI~~ 站在塔下按T打开升级菜单 WIP - IAN
   - 适配TurretUpdate接口
- [ ] 扳手指向的Turret可视化
  - 人物坐标+扳手朝向的transform.forward*一个数，获取该点的坐标最近的扳手，判断其与人物距离是否小于一定值，激活TurretShineBehavior
- [ ] 开局之前的商店，可以选择炮塔与一次性道具
- [ ] 道具栏中的收纳好的炮塔，允许开局后部署
- 更多炮塔种类
  - [x] 三发炮塔：同时向瞄准方向和左右一定角度打出三发子弹
  - [x] 真·炮塔：AOE伤害
  - 想到的可以再往上加
- 更多敌人种类
  - [x] 三发步兵：同时打出三发子弹
  - [x] 鬼火射手：朝Hero打出追踪的鬼火，移动缓慢，一段时间后消失
  - [ ] 自爆卡车：打死后自爆，对范围内的炮塔和Hero造成AOE伤害
  - 想到的可以再往上加
- 更多武器种类
  - [x] 手枪
  - [x] AK：射速++，伤害+
  - [x] MP5：射速++++，伤害-
- 道具栏
  - [ ] ~~void StartCooldDown(float time, int index) 道具冷却视觉效果~~ 暂时不做了 时间性价比不高
  - [x] void SetItemCount(int index, int count): 设置右下角显示剩余数量 
 - [x] **重叠效果** 在Project Settings/Graphics/Camera Settings 把Transperancy Mode改成Custom Axis, Transparency Sort Axis改成 X:0 Y:1 Z:0）
